<a href="https://colab.research.google.com/github/nollamae7-spec/DSRSP-Solar-Flares/blob/Exploring-duplicates/DSHRP_Solar_Flares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
url = 'https://github.com/frontiertechinstitute/datasets/raw/main/Solar%20Flares%20Dataset/solar_flares.csv'
df = pd.read_csv(url)

df.head(10)

,zurich_class,largest_spot_size,spot_distribution,activity,evolution,prev_24hr_flare_activity,historically_complex,became_complex_this_pass,area,area_largest_spot,c_class_flares,m_class_flares,x_class_flares
0,C,S,O,1,2,1,1,2,1,2,0,0,0
1,D,S,O,1,3,1,1,2,1,2,0,0,0
2,C,S,O,1,3,1,1,2,1,1,0,0,0
3,D,S,O,1,3,1,1,2,1,2,0,0,0
4,D,A,O,1,3,1,1,2,1,2,0,0,0
5,D,A,O,1,2,1,1,2,1,2,0,0,0
6,D,A,O,1,2,1,1,2,1,1,0,0,0
7,D,A,O,1,2,1,1,2,1,2,0,0,0
8,D,K,O,1,3,1,1,2,1,2,0,0,0
9,C,R,O,1,3,1,1,2,1,1,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   zurich_class              1389 non-null   object
 1   largest_spot_size         1389 non-null   object
 2   spot_distribution         1389 non-null   object
 3   activity                  1389 non-null   int64
 4   evolution                 1389 non-null   int64
 5   prev_24hr_flare_activity  1389 non-null   int64
 6   historically_complex      1389 non-null   int64
 7   became_complex_this_pass  1389 non-null   int64
 8   area                      1389 non-null   int64
 9   area_largest_spot         1389 non-null   int64
 10  c_class_flares            1389 non-null   int64
 11  m_class_flares            1389 non-null   int64
 12  x_class_flares            1389 non-null   int64
dtypes: int64(10), object(3)
memory usage: 141.2+ KB

In [ ]:
duplicated_rows = df[df.duplicated()]
print(duplicated_rows)

     zurich_class largest_spot_size spot_distribution  activity  evolution  \
3               D                 S                 O         1          3
7               D                 A                 O         1          2
15              B                 X                 O         1          3
21              B                 X                 O         1          3
23              B                 X                 O         1          2
...           ...               ...               ...       ...        ...
1384            H                 S                 X         1          2
1385            H                 S                 X         2          2
1386            C                 S                 O         1          2
1387            H                 R                 X         1          2
1388            B                 X                 O         1          1

      prev_24hr_flare_activity  historically_complex  \
3                            1                     1
7                            1                     1
15                           1                     1
21                           1                     1
23                           1                     1
...                        ...                   ...
1384                         1                     1
1385                         1                     1
1386                         1                     2
1387                         1                     1
1388                         1                     1

      became_complex_this_pass  area  area_largest_spot  c_class_flares  \
3                            2     1                  2               0
7                            2     1                  2               0
15                           2     1                  1               0
21                           2     1                  1               0
23                           2     1                  1               0
...                        ...   ...                ...             ...
1384                         1     1                  1               0
1385                         2     1                  1               0
1386                         2     1                  1               0
1387                         2     1                  1               0
1388                         2     1                  1               0

      m_class_flares  x_class_flares
3                  0               0
7                  0               0
15                 0               0
21                 0               0
23                 0               0
...              ...             ...
1384               0               0
1385               0               0
1386               0               0
1387               0               0
1388               0               0

[862 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   zurich_class              1389 non-null   object
 1   largest_spot_size         1389 non-null   object
 2   spot_distribution         1389 non-null   object
 3   activity                  1389 non-null   int64
 4   evolution                 1389 non-null   int64
 5   prev_24hr_flare_activity  1389 non-null   int64
 6   historically_complex      1389 non-null   int64
 7   became_complex_this_pass  1389 non-null   int64
 8   area                      1389 non-null   int64
 9   area_largest_spot         1389 non-null   int64
 10  c_class_flares            1389 non-null   int64
 11  m_class_flares            1389 non-null   int64
 12  x_class_flares            1389 non-null   int64
dtypes: int64(10), object(3)
memory usage: 141.2+ KB

Values =

x_class_flares = 0, 1, 2

In [ ]:
df["x_class_flares"].unique()

array([0, 1, 2])

In [ ]:
df[df['x_class_flares'].duplicated()== True]

,zurich_class,largest_spot_size,spot_distribution,activity,evolution,prev_24hr_flare_activity,historically_complex,became_complex_this_pass,area,area_largest_spot,c_class_flares,m_class_flares,x_class_flares
1,D,S,O,1,3,1,1,2,1,2,0,0,0
2,C,S,O,1,3,1,1,2,1,1,0,0,0
3,D,S,O,1,3,1,1,2,1,2,0,0,0
4,D,A,O,1,3,1,1,2,1,2,0,0,0
5,D,A,O,1,2,1,1,2,1,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,H,S,X,1,2,1,1,1,1,1,0,0,0
1385,H,S,X,2,2,1,1,2,1,1,0,0,0
1386,C,S,O,1,2,1,2,2,1,1,0,0,0
1387,H,R,X,1,2,1,1,2,1,1,0,0,0
1388,B,X,O,1,1,1,1,2,1,1,0,0,0

In [ ]:
df[df["x_class_flares"]==0] and df[df['x_class_flares'].duplicated()== True]

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().